- name: PHP-FPM ROLE | Install list of php packages
  apt: name={{item}}
  with_items:
    - php5-cli
    - php-pear
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-intl
    - php5-fpm
    - php5-memcached
    - php5-xsl
    - imagemagick
    - php5-imagick