---

- apt_repository:
   repo: 'ppa:ondrej/php'

- name: Updating apt cache
  apt:
    update_cache: yes
  become: true

- name: Install php packages for php 5.6
  apt: name={{item}}
  with_items:
   - php5.6-cli
   - php5.6-curl
   - php5.6-gd
   - php5.6-mcrypt
   - php5.6-intl
   - php5.6-fpm
   - php5.6-memcached
   - imagemagick
   - php5.6-imagick
   - php5.6-xml
   - php5.6-mbstring
  when: default_php_version == 5.6

- template:
   src: ../templates/php5.6/cli/php.ini.j2
   dest: /etc/php/5.6/cli/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 5.6

- template:
   src: ../templates/php5.6/fpm/php.ini.j2
   dest: /etc/php/5.6/fpm/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 5.6

- template:
   src: ../templates/php5.6/fpm/pool.d/php.conf.j2
   dest: /etc/php/5.6/fpm/pool.d/php.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 5.6

- file:
   path: /etc/php/5.6/fpm/pool.d/www.conf
   state: absent
  when: default_php_version == 5.6

- name: PHP-FPM ROLE | Starting PHP-FPM
  service:
   name: php5.6-fpm
   state: restarted
  when: default_php_version == 5.6



- name: Install php packages for php 7.0
  apt: name={{item}}
  with_items:
   - php7.0-cli
   - php7.0-curl
   - php7.0-gd
   - php7.0-mcrypt
   - php7.0-intl
   - php7.0-fpm
   - php7.0-memcached
   - imagemagick
   - php7.0-imagick
   - php7.0-xml
   - php7.0-mbstring
  when: default_php_version == 7.0

- template:
   src: ../templates/php7.0/cli/php.ini.j2
   dest: /etc/php/7.0/cli/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.0

- template:
   src: ../templates/php7.0/fpm/php.ini.j2
   dest: /etc/php/7.0/fpm/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.0

- template:
   src: ../templates/php7.0/fpm/pool.d/php.conf.j2
   dest: /etc/php/7.0/fpm/pool.d/php.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.0

- file:
   path: /etc/php/7.0/fpm/pool.d/www.conf
   state: absent
  when: default_php_version == 7.0

- name: PHP-FPM ROLE | Starting PHP-FPM
  service:
   name: php7.0-fpm
   state: restarted
  when: default_php_version == 7.0


- name: Install php packages for php 7.1
  apt: name={{item}}
  with_items:
   - php7.1-cli
   - php7.1-curl
   - php7.1-gd
   - php7.1-mcrypt
   - php7.1-intl
   - php7.1-fpm
   - php7.1-memcached
   - imagemagick
   - php7.1-imagick
   - php7.1-xml
   - php7.1-mbstring
  when: default_php_version == 7.1

- template:
   src: ../templates/php7.1/cli/php.ini.j2
   dest: /etc/php/7.1/cli/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.1

- template:
   src: ../templates/php7.1/fpm/php.ini.j2
   dest: /etc/php/7.1/fpm/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.1

- template:
   src: ../templates/php7.1/fpm/pool.d/php.conf.j2
   dest: /etc/php/7.1/fpm/pool.d/php.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.1

- file:
   path: /etc/php/7.1/fpm/pool.d/www.conf
   state: absent
  when: default_php_version == 7.1

- name: PHP-FPM ROLE | Starting PHP-FPM
  service:
   name: php7.1-fpm
   state: restarted
  when: default_php_version == 7.1


- name: Install php packages for php 7.2
  apt: name={{item}}
  with_items:
   - php7.2-cli
   - php7.2-curl
   - php7.2-gd
   - php7.2-intl
   - php7.2-fpm
   - php7.2-memcached
   - imagemagick
   - php7.2-imagick
   - php7.2-xml
   - php7.2-mbstring
  when: default_php_version == 7.2

- template:
   src: ../templates/php7.2/cli/php.ini.j2
   dest: /etc/php/7.2/cli/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.2

- template:
   src: ../templates/php7.2/fpm/php.ini.j2
   dest: /etc/php/7.2/fpm/php.ini
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.2

- template:
   src: ../templates/php7.2/fpm/pool.d/php.conf.j2
   dest: /etc/php/7.2/fpm/pool.d/php.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: default_php_version == 7.2

- file:
   path: /etc/php/7.2/fpm/pool.d/www.conf
   state: absent
  when: default_php_version == 7.2

- name: PHP-FPM ROLE | Starting PHP-FPM
  service:
   name: php7.2-fpm
   state: restarted
  when: default_php_version == 7.2
